# Writes the build identity headers that the version resources, the version displays, and the
# debug log's startup banner report.
#
# The version header follows the project version and so changes only when a release cycle
# opens; the build header follows HEAD and changes with every commit. They are separate so
# that a new commit does not recompile everything that merely needs the version.
#
# Run both at configure time and once per build, so the recorded commit follows HEAD without
# a reconfigure. A header is only rewritten when its contents change, so an ordinary rebuild
# does not force a recompile.
#
# Expects OPENTS_VERSION_MAJOR, OPENTS_VERSION_MINOR, OPENTS_VERSION_PATCH,
# OPENTS_VERSION_PRERELEASE, OPENTS_OFFICIAL_BUILD, OPENTS_SOURCE_DIR, OPENTS_VERSION_HEADER,
# and OPENTS_STAMP_HEADER to be set.

# The packed form spends one byte on each component, and the save and network stamps are
# compared for exact equality. Development snapshots in one cycle deliberately share it;
# the separate commit stamp identifies the build for diagnostics. A component that does not
# fit would silently collide with another release-cycle version.
foreach(part MAJOR MINOR PATCH)
    if(OPENTS_VERSION_${part} GREATER 255)
        message(FATAL_ERROR
            "OpenTS version component ${part} is ${OPENTS_VERSION_${part}}; "
            "the packed version stamp allows at most 255.")
    endif()
endforeach()

math(EXPR OPENTS_VERSION_PACKED
    "(${OPENTS_VERSION_MAJOR} << 16) | (${OPENTS_VERSION_MINOR} << 8) | ${OPENTS_VERSION_PATCH}"
    OUTPUT_FORMAT HEXADECIMAL)

set(OPENTS_VERSION "${OPENTS_VERSION_MAJOR}.${OPENTS_VERSION_MINOR}.${OPENTS_VERSION_PATCH}")
set(OPENTS_IS_PRERELEASE 0)
if(NOT OPENTS_VERSION_PRERELEASE STREQUAL "")
    string(APPEND OPENTS_VERSION "-${OPENTS_VERSION_PRERELEASE}")
    set(OPENTS_IS_PRERELEASE 1)
endif()

set(VERSION_CONTENT
"/*******************************************************************************
 *                                O P E N  T S
 *******************************************************************************
 * SPDX-License-Identifier: GPL-3.0-or-later
 * Copyright 2026 OpenTS contributors
 *
 * See LICENSE.md for applicable additional terms and warranty disclaimers.
 ******************************************************************************/

/* Generated by cmake/GitStamp.cmake. Edits are overwritten by the next build. */

#pragma once

#define OPENTS_VERSION_MAJOR  ${OPENTS_VERSION_MAJOR}
#define OPENTS_VERSION_MINOR  ${OPENTS_VERSION_MINOR}
#define OPENTS_VERSION_PATCH  ${OPENTS_VERSION_PATCH}

/* The save and network stamps. A prerelease is not distinguished here: it carries the
   identity of the release it leads up to. */
#define OPENTS_VERSION_PACKED ${OPENTS_VERSION_PACKED}

#define OPENTS_VERSION        \"${OPENTS_VERSION}\"
#define OPENTS_IS_PRERELEASE  ${OPENTS_IS_PRERELEASE}

/* The numeric version fields of a VERSIONINFO resource. */
#define OPENTS_RC_FILEVERSION ${OPENTS_VERSION_MAJOR},${OPENTS_VERSION_MINOR},${OPENTS_VERSION_PATCH},0

/* A VERSIONINFO file flag, so that the resource compiler needs no prerelease branch of its
   own. It resolves only where a resource script has included the Windows version headers. */
#if OPENTS_IS_PRERELEASE
#define OPENTS_RC_PRERELEASE_FLAG VS_FF_PRERELEASE
#else
#define OPENTS_RC_PRERELEASE_FLAG 0x0L
#endif
")

set(OPENTS_COMMIT "unknown")
set(OPENTS_BRANCH "unknown")
set(OPENTS_COMMIT_DATE "unknown")
set(OPENTS_COMMIT_DIRTY 0)

find_package(Git QUIET)

# A build from a source archive has no repository, and git need not be installed at all.
# Neither is an error; the banner simply reports what it does not know.
if(GIT_FOUND AND EXISTS "${OPENTS_SOURCE_DIR}/.git")

    execute_process(
        COMMAND "${GIT_EXECUTABLE}" rev-parse --short HEAD
        WORKING_DIRECTORY "${OPENTS_SOURCE_DIR}"
        OUTPUT_VARIABLE GIT_COMMIT
        OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_QUIET
        RESULT_VARIABLE GIT_COMMIT_RESULT
    )
    if(GIT_COMMIT_RESULT EQUAL 0 AND GIT_COMMIT)
        set(OPENTS_COMMIT "${GIT_COMMIT}")
    endif()

    execute_process(
        COMMAND "${GIT_EXECUTABLE}" rev-parse --abbrev-ref HEAD
        WORKING_DIRECTORY "${OPENTS_SOURCE_DIR}"
        OUTPUT_VARIABLE GIT_BRANCH
        OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_QUIET
        RESULT_VARIABLE GIT_BRANCH_RESULT
    )
    if(GIT_BRANCH_RESULT EQUAL 0 AND GIT_BRANCH AND NOT GIT_BRANCH STREQUAL "HEAD")
        set(OPENTS_BRANCH "${GIT_BRANCH}")
    else()
        # A detached HEAD reports its branch as the word HEAD, which names nothing. Checking
        # out a tag does that, and so does a continuous integration build of a pull request.
        # Report a ref that points at the commit instead, preferring a tag.
        execute_process(
            COMMAND "${GIT_EXECUTABLE}" for-each-ref --points-at HEAD "--format=%(refname)"
                    refs/tags refs/heads refs/remotes
            WORKING_DIRECTORY "${OPENTS_SOURCE_DIR}"
            OUTPUT_VARIABLE GIT_POINTING_REFS
            OUTPUT_STRIP_TRAILING_WHITESPACE
            ERROR_QUIET
            RESULT_VARIABLE GIT_POINTING_RESULT
        )
        if(GIT_POINTING_RESULT EQUAL 0 AND GIT_POINTING_REFS)
            string(REPLACE "\n" ";" GIT_POINTING_REFS "${GIT_POINTING_REFS}")
            foreach(prefix "refs/tags/" "refs/heads/" "refs/remotes/")
                foreach(ref IN LISTS GIT_POINTING_REFS)
                    string(STRIP "${ref}" ref)
                    # refs/remotes/<remote>/HEAD only records where a remote points.
                    if(ref MATCHES "^${prefix}" AND NOT ref MATCHES "/HEAD$")
                        string(REPLACE "${prefix}" "" OPENTS_BRANCH "${ref}")
                        break()
                    endif()
                endforeach()
                if(NOT OPENTS_BRANCH STREQUAL "unknown")
                    break()
                endif()
            endforeach()
        endif()
    endif()

    execute_process(
        COMMAND "${GIT_EXECUTABLE}" log -1 "--format=%cd" "--date=format:%Y-%m-%d %H:%M:%S"
        WORKING_DIRECTORY "${OPENTS_SOURCE_DIR}"
        OUTPUT_VARIABLE GIT_DATE
        OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_QUIET
        RESULT_VARIABLE GIT_DATE_RESULT
    )
    if(GIT_DATE_RESULT EQUAL 0 AND GIT_DATE)
        set(OPENTS_COMMIT_DATE "${GIT_DATE}")
    endif()

    # Untracked files are excluded deliberately: a scratch file beside the sources does not
    # make the built code differ from the commit.
    execute_process(
        COMMAND "${GIT_EXECUTABLE}" status --porcelain --untracked-files=no
        WORKING_DIRECTORY "${OPENTS_SOURCE_DIR}"
        OUTPUT_VARIABLE GIT_STATUS
        OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_QUIET
        RESULT_VARIABLE GIT_STATUS_RESULT
    )
    if(GIT_STATUS_RESULT EQUAL 0 AND NOT GIT_STATUS STREQUAL "")
        set(OPENTS_COMMIT_DIRTY 1)
    endif()

endif()

# What the player sees. An official build is the version alone; anything else names the commit
# it came from, because a version number alone cannot identify a build taken from mid-cycle.
set(OPENTS_BUILD_DESCRIPTION "${OPENTS_COMMIT} on ${OPENTS_BRANCH}")
if(OPENTS_COMMIT_DIRTY)
    string(APPEND OPENTS_BUILD_DESCRIPTION " (modified)")
endif()

if(OPENTS_OFFICIAL_BUILD)
    set(OPENTS_VERSION_DISPLAY "${OPENTS_VERSION} (${OPENTS_ARCH})")
elseif(OPENTS_COMMIT STREQUAL "unknown")
    set(OPENTS_VERSION_DISPLAY "${OPENTS_VERSION} (${OPENTS_ARCH})")
elseif(OPENTS_COMMIT_DIRTY)
    set(OPENTS_VERSION_DISPLAY "${OPENTS_VERSION} (${OPENTS_ARCH}) (${OPENTS_COMMIT}, modified)")
else()
    set(OPENTS_VERSION_DISPLAY "${OPENTS_VERSION} (${OPENTS_ARCH}) (${OPENTS_COMMIT})")
endif()

set(STAMP_CONTENT
"/*******************************************************************************
 *                                O P E N  T S
 *******************************************************************************
 * SPDX-License-Identifier: GPL-3.0-or-later
 * Copyright 2026 OpenTS contributors
 *
 * See LICENSE.md for applicable additional terms and warranty disclaimers.
 ******************************************************************************/

/* Generated by cmake/GitStamp.cmake. Edits are overwritten by the next build. */

#pragma once

#include \"opents_version.h\"

#define OPENTS_COMMIT            \"${OPENTS_COMMIT}\"
#define OPENTS_BRANCH            \"${OPENTS_BRANCH}\"
#define OPENTS_COMMIT_DATE       \"${OPENTS_COMMIT_DATE}\"
#define OPENTS_COMMIT_DIRTY      ${OPENTS_COMMIT_DIRTY}

/* The commit and branch as one line, for reports with no room to lay the parts out. */
#define OPENTS_BUILD_DESCRIPTION \"${OPENTS_BUILD_DESCRIPTION}\"

/* The version as the player sees it. A build that is not marked official names its commit. */
#define OPENTS_VERSION_DISPLAY   \"${OPENTS_VERSION_DISPLAY}\"
")

# Rewriting an identical header would make every build recompile its consumers.
function(write_if_changed path content)
    set(existing "")
    if(EXISTS "${path}")
        file(READ "${path}" existing)
    endif()
    if(NOT existing STREQUAL content)
        file(WRITE "${path}" "${content}")
        set(WROTE_HEADER TRUE PARENT_SCOPE)
    endif()
endfunction()

write_if_changed("${OPENTS_VERSION_HEADER}" "${VERSION_CONTENT}")
write_if_changed("${OPENTS_STAMP_HEADER}" "${STAMP_CONTENT}")

if(WROTE_HEADER)
    message(STATUS "OpenTS: build stamp ${OPENTS_VERSION_DISPLAY} on ${OPENTS_BRANCH}")
endif()
